404 Client Error: Not Found for url: https://huggingface.co/castorini/tct_colbert-msmardex/resolve/main/config.json
Traceback (most recent call last):
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/transformers/configuration_utils.py", line 520, in get_config_dict
    user_agent=user_agent,
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/transformers/file_utils.py", line 1378, in cached_path
    local_files_only=local_files_only,
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/transformers/file_utils.py", line 1541, in get_from_cache
    r.raise_for_status()
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/castorini/tct_colbert-msmardex/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/pyserini/dindex/__main__.py", line 54, in <module>
    model = init_encoder(args.encoder, device=args.device)
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/pyserini/dindex/__main__.py", line 31, in init_encoder
    return TctColBertDocumentEncoder(encoder, device=device)
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/pyserini/dindex/_base.py", line 33, in __init__
    self.model = BertModel.from_pretrained(model_name)
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/transformers/modeling_utils.py", line 1200, in from_pretrained
    **kwargs,
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/transformers/configuration_utils.py", line 455, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/tmp/gecr/rachael-scai/env/lib/python3.6/site-packages/transformers/configuration_utils.py", line 532, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'castorini/tct_colbert-msmardex'. Make sure that:

- 'castorini/tct_colbert-msmardex' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'castorini/tct_colbert-msmardex' is the correct path to a directory containing a config.json file


